#!/usr/bin/env sh

wget "http://download.jetbrains.com/idea/ideaIC-138.777.tar.gz" -O - \
  | tar -C ~/.local/share/ -zxvf -
mv ~/.local/share/idea-IC-138.777 ~/.local/share/idea
patch -p1 ~/.local/share/idea/bin/idea.sh < idea/idea.sh.patch
