#!/usr/bin/env sh

set -e
set -u
set -x

if ! git fetch origin release
then
        git init
        git config core.sparseCheckout true
        mkdir .git/info
        echo "OTF/**/*" >> .git/info/sparse-checkout
        git remote add --master release origin 'https://github.com/adobe-fonts/source-code-pro.git'
        git fetch --depth 1 origin release
fi
git checkout release
